services:
  sender:
    build:
      context: ..
      dockerfile: deephaven-sender/Dockerfile
    networks:
      - deephaven
    environment:
      DEEPHAVEN_TARGET: deephaven:10000
    restart: "no"

networks:
  deephaven:
    name: deephaven
    external: true
